### ISSUE TITLE
issue with media player

### ISSUE THREAD

**Issue by siatrasapost** [dimitrismoschou/musicapp#7]
music keeps playing after user has logged out, i don't think this should happen.

**Comment by siatrasapost** [comment]
also after search by genre previous and next button should not select a song from another genre, but we can code a toast saying "other songs you might like"

**Comment by AxilleasGR** [comment]
> also after search by genre previous and next button should not select a song from another genre, but we can code a toast saying "other songs you might like"

Please create a new issue so we can close this one

**Comment by AxilleasGR** [comment]
Bug fixed from #16 pull request , issue closed.
